const header = document.getElementById('quote')
var imageIndexes = [];
const quotes = [
	'Run it back',
	'Hard to see reason',
	'THEY PULL MY DIGITAL LEASH',
	'GRAPHICS',
	'Session terminated',
	'PAPITAS',
	'Here comes the sun',
	'Take a ride, take a shot now',
	'I wanna take you through a wasteland I like to call my home',
	'Take all your pieces home',
	'Spastic, plastic, battery acid',
	'LOOK ME IN MY BRAND NEW EYE',
	'Will you kill me if I say please?',
	'And the failure of the Nile',
	'Fill my empty bones',
	'Cut your hair and change your name',
	'Asbestos Lead Asbestos',
	'It\'s just a natural disaster that You\'ve left behind',
	'Heaven isn\'t on my side',
	'Pack it up and find peace',
	'Find a way back now',
	'Ironic touch',
	'(SIC)',
	'Running out of ways to run',
	'Little soldiers in a row',
	'So dramatic, every time guaranteed',
	'It tastes the same for someone else',
	'Score love as a painkiller',
	'Can\'t get away from the moment',
	'Running in a rat maze',
	'Nothing tastes better than sweet memory',
	'Suffocatin\' on my own',
	'I wait on you inside the bottom of the deep blue',
	'HOW YOU FREEZE ME',
	'I\'m not the only one',
	'The red flag waving never meant the same',
	'It\'s choice now, maybe',
	'Will I ever learn?',
	'I don\'t trust these eyes',
	'Wipe that disgrace off your face',
	'Cash in on the tragedy',
	'Gimme something to hold true, gimme something to sing about',
	'A little water please, I taste you all over my teeth',
	'Tell us what you see?',
	'Indeed a fool am I',
	'I won\'t give another life to you',
	'I wanted something special before',
	'Cultures weren\'t opinions',
	'Pull you in before you fall',
	'Where have I been all this time?',
	'Another message I can\'t read',
	'A new religion prescribed',
	'There is no one here but me',
	'God is wearing black',
	'Rose tinted eyes',
	'20 days, 7 hours alone',
	'Along the way, I had to sell my soul',
	'Not everyone deserves the sun',
	'Have your whole click served',
	'My mercury\'s in retrograde',
	'HOUSE REAL BIG',
	'I WAS UNAWARE ☝️🤓',
	'Midnight madness',
	'JUNGLE IS MASSIVE',
	'Shock me like an electric eel',
	'Turn the academy down',
	'It\'s R-A-W',
	'Can\'t believe how much fun we\'re having',
	'I PUT ON',
	'Freeze, now take my picture',
	'Into your garden',
	'Bury me softly in this womb',
	'\'TILL WE DIE',
	'Auto pilot no control',
	'They\'d think that I\'d finally lost it completely',
	'Breathe out, so I can breathe you in',
	'You\'re solid gold, I\'ll see you in hell',
	'I\'m too wrong to get right',
	'Just drool in the dark as you stare at the lights',
	'Just live \'til you die',
	'Flies buzzing around my head',
	'I think I\'m dumb',
	'On a long slow goodbye',
	'Take a picture and bury it all away',
	'I thought you died alone',
	'BLOW UP THE OUTSIDE WORLD',
	'Room by room, patiently',
	'Bittersweet migraine in my head',
	'And I\'ll hear you scream again',
	'Heaven beside you, hell within',
	'TO THE WINDOW',
	'Belts it\'s so hot it will even make heat melt',
	'O beloved Mother of Liberty, hold me in your arms',
	'Hurry up and wait forever',
	'You\'re running after something that you\'ll never kill',
	'Any minute now',
	'Got the beat on suicide',
	'Take 3 jams and hold\'em',
	'WHITE WHALE, HOLY GRAIL',
	'Feels just like it should',
	'Secure a full view',
	'Everyones a bad man now',
	'And that\'s fresh fresh fresh',
	'Just bet you might win',
	'It\'s all my head I know',
	'And your nose is bleeding',
	'And you don\'t taste like her and you never ever will',
	'Milk of amnesia',
	'For the first time again',
	'A moment in between the rest',
	'Test & recognise',
	'Got a lotta nice things to say',
	'I\'m not searching for a miracle',
	'\'Cause I do',
	'Felt like summer to my December',
	'Maybe I wasn\'t there',
	'Like it\'s \'75 again',
	'Open mouth swallowing us',
	'Say it to the man who profits, and the bastard walks by',
	'Sun digs its heels to taunt you',
	'But I\'ll know, I\'ll know',
	'Choking on your alibis',
	'Des yeux sans visage',
	'Dancing on wire both ends are on fire',
	'Chasing down the moon',
	'I daydream until all the blue is gone',
	'Does anyone ever get this right?',
	'Angels lie to keep control',
	'It\'s stress relief from everything',
	'Should\'ve lasted many many years',
	'We\'re hostages of geography',
	'HANDS ON MY FACE, OVERBEARING, I CAN\'T GET OUT',
	'I know why you plague yourself',
	'ALL THE MONEY IN THE WORLD CAN\'T BUY ME',
	'Bite your tongue',
	'Words ain\'t free, like you and me',
	'So glad you could stay forever',
	'They said it changes when the sun goes down',
	'B-E-I-J-I-N-G',
	'Hour after - Our work is - Never over',
	'Orphans of the universe',
	'Take the highway 95!',
	'My teeth are yellow, hello world, Would you like me a little better if they were white like yours?',
	'All the signs I don\'t read',
];

for(var i = 0; i <= 78; i++){
	imageIndexes.push(i);
};

let num = Math.floor(Math.random() * imageIndexes.length);
let pick = Math.floor(Math.random() * quotes.length);

window.onload = function() {
	header.innerText = quotes[pick];
	document.body.style.backgroundImage = `url(gallery/renders/render${num}.webp)`;
};
